# Generated by Django 3.0.7 on 2020-06-29 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hnet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raw',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='structuredpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structuredpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
