# Generated by Django 3.0.7 on 2020-06-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnet', '0002_auto_20200629_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw',
            name='external_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
