# Generated by Django 3.0.7 on 2020-07-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnet', '0004_auto_20200705_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredpost',
            name='categories',
            field=models.ManyToManyField(blank=True, to='hnet.Category'),
        ),
        migrations.AlterField(
            model_name='structuredpost',
            name='positions',
            field=models.ManyToManyField(blank=True, to='hnet.Position'),
        ),
    ]
