# Generated by Django 3.0.7 on 2020-07-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnet', '0005_auto_20200705_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuredpost',
            name='categories',
        ),
        migrations.AddField(
            model_name='structuredpost',
            name='primary_categories',
            field=models.ManyToManyField(blank=True, related_name='primary_posts', to='hnet.Category'),
        ),
        migrations.AddField(
            model_name='structuredpost',
            name='secondary_categories',
            field=models.ManyToManyField(blank=True, related_name='secondary_posts', to='hnet.Category'),
        ),
    ]
