# Generated by Django 3.0.7 on 2020-07-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnet', '0007_auto_20200706_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
