# Generated by Django 3.0.7 on 2020-12-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnet', '0011_failedrenderpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredpost',
            name='contact',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
