# Generated by Django 3.0.7 on 2020-12-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hnet', '0012_auto_20201201_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuredpost',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hnet.Category'),
        ),
    ]
